const Data = [
  {
    id: 1,
    image: "https://i.postimg.cc/kMTmXd2W/icon.png",
    category: "IN_PROGRESS",
    project: "Penny Coin",
    dollar: "$PENNY",
    soft: 75,
    hard: 150,
    min: 0.1,
    max: 5,
    liquidity: 100,
    Progress: 30.1213123,
  },
  {
    id: 2,
    image: "https://i.postimg.cc/kMTmXd2W/icon.png",
    category: "UPCOMING",
    project: "Penny Coin",
    dollar: "$PENNY",
    soft: 75,
    hard: 150,
    min: 0.1,
    max: 5,
    liquidity: 100,
    Progress: 6.3,
  },
  {
    id: 3,
    image: "https://i.postimg.cc/kMTmXd2W/icon.png",
    category: "UPCOMING",
    project: "Penny Coin",
    dollar: "$PENNY",
    soft: 75,
    hard: 150,
    min: 0.1,
    max: 5,
    liquidity: 100,
    Progress: 6.3,
  },
  {
    id: 4,
    image: "https://i.postimg.cc/kMTmXd2W/icon.png",
    category: "IN_PROGRESS",
    project: "Penny Coin",
    dollar: "$PENNY",
    soft: 75,
    hard: 150,
    min: 0.1,
    max: 5,
    liquidity: 100,
    Progress: 6.3,
  },
  {
    id: 5,
    image: "https://i.postimg.cc/kMTmXd2W/icon.png",
    category: "ENDED",
    project: "Penny Coin",
    dollar: "$PENNY",
    soft: 75,
    hard: 150,
    min: 0.1,
    max: 5,
    liquidity: 100,
    Progress: 6.3,
  },
  {
    id: 6,
    image: "https://i.postimg.cc/kMTmXd2W/icon.png",
    category: "UPCOMING",
    project: "Penny Coin",
    dollar: "$PENNY",
    soft: 75,
    hard: 150,
    min: 0.1,
    max: 5,
    liquidity: 100,
    Progress: 6.3,
  },
  {
    id: 7,
    image: "https://i.postimg.cc/kMTmXd2W/icon.png",
    category: "CANCELED",
    project: "Penny Coin",
    dollar: "$PENNY",
    soft: 75,
    hard: 150,
    min: 0.1,
    max: 5,
    liquidity: 100,
    Progress: 6.3,
  },
  {
    id: 8,
    image: "https://i.postimg.cc/kMTmXd2W/icon.png",
    category: "CANCELED",
    project: "Penny Coin",
    dollar: "$PENNY",
    soft: 75,
    hard: 150,
    min: 0.1,
    max: 5,
    liquidity: 100,
    Progress: 6.3,
  },
];

export default Data;
